name: fast-hit
channels:
  - bioconda
  - gpytorch
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - tqdm=4.61.1
  - biopython=1.79
  - python=3.7.10
  - numpy=1.21.0
  - scipy=1.7.0
  - pandas=1.3.0
  - scikit-learn=0.24.2
  - pytorch=1.9.0
  - cudatoolkit=10.2.89
  - skorch=0.10.0
  - gpytorch=1.5.0
  - editdistance=0.5.3
  - seaborn=0.11.1
