from dataclasses import dataclass
from .onehot import OneHot
from .georgiev import Georgiev
from .tape import TAPE
from .tape_msa import TAPEMsa
from .esm import ESM
from .esm_msa import ESMMsa
from .prot_trans import ProtTrans
from .esm_tokenizer import ESM_Tokenizer
