from fasthit.encoders.onehot import OneHot
from fasthit.encoders.extend import Extend
from fasthit.encoders.extend_half import ExtendHalf
from fasthit.encoders.georgiev import Georgiev
from fasthit.encoders.tape import TAPE
from fasthit.encoders.esm import ESM
from fasthit.encoders.esm_mpi import ESMMPI
from fasthit.encoders.esm_nompi import ESMNOMPI
from fasthit.encoders.prot_trans import ProtTrans